export const productCarouselBreakpoints = {
  400: {
    slidesPerView: 2,
    spaceBetween: 0,
    allowTouchMove: true,
    slidesPerGroup: 2,
    loop: false,
    cssMode: true,
  },
  480: {
    slidesPerView: 2,
    spaceBetween: 4,
    allowTouchMove: true,
    slidesPerGroup: 2,
    loop: false,
    cssMode: true,
  },
  670: {
    slidesPerView: 3,
    spaceBetween: 8,
    allowTouchMove: true,
    slidesPerGroup: 3,
    loop: false,
    cssMode: true,
  },
  767: {
    slidesPerView: 3,
    spaceBetween: 8,
    slidesPerGroup: 3,
    loop: false,
    cssMode: true,
  },
  980: {
    slidesPerView: 4,
    spaceBetween: 8,
    slidesPerGroup: 4,
    loop: true,
    cssMode: true,
  },
  1023: {
    slidesPerView: 4,
    spaceBetween: 8,
    slidesPerGroup: 4,
    loop: true,
    allowTouchMove: false,
    cssMode: true,
  },
  1279: {
    slidesPerView: 5,
    spaceBetween: 8,
    slidesPerGroup: 5,
    loop: true,
    allowTouchMove: false,
    cssMode: false,
  },
};
