export enum ENUM_API_ERRORS {
  //Auth
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN',
  INVALID_LOGIN_METHOD = 'INVALID_LOGIN_METHOD',

  //User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UPDATE_USER_AT_LEAST_ONE_PARAMETER = 'UPDATE_USER_AT_LEAST_ONE_PARAMETER', // should be dto error?

  //Params
  INVALID_MONGO_ID = 'INVALID_MONGO_ID',
  INVALID_ORDER_ID = 'INVALID_ORDER_ID',
  REQUEST_PARAM_REQUIRED = 'REQUEST_PARAM_REQUIRED',
  QUERY_PARAM_REQUIRED = 'QUERY_PARAM_REQUIRED',

  //Product
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_CATEGORY_IMAGE_REQUIRED = 'PRODUCT_CATEGORY_IMAGE_REQUIRED', // should be dto error?
  PRODUCT_CATEGORY_DUPLICATE_SLUG = 'PRODUCT_CATEGORY_DUPLICATE_SLUG',
  PRODUCT_IMAGES_LIMIT_EXCEEDED = 'PRODUCT_IMAGES_LIMIT_EXCEEDED', // should be dto error?
  PRODUCT_DUPLICATE_SLUG = 'PRODUCT_DUPLICATE_SLUG',
  PRODUCT_CATEGORY_NOT_FOUND = 'PRODUCT_CATEGORY_NOT_FOUND',
  PRODUCT_SKU_REQUIRED = 'PRODUCT_SKU_REQUIRED', // should be dto error?
  PRODUCT_SKU_MIN_LENGTH = 'PRODUCT_SKU_MIN_LENGTH', // should be dto error?

  //Shipping
  SHIPPING_METHOD_DUPLICATE = 'SHIPPING_METHOD_DUPLICATE',
  SHIPPING_COST_NOT_FOUND = 'SHIPPING_COST_NOT_FOUND',

  //Coupon
  COUPON_NOT_FOUND = 'COUPON_NOT_FOUND',
  COUPON_USAGE_LIMIT_REACHED = 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_ALREADY_USED = 'COUPON_ALREADY_USED',
  DUPLICATE_COUPON_CODE = 'DUPLICATE_COUPON_CODE',

  //Stripe
  INVALID_STRIPE_SESSION_ID = 'INVALID_STRIPE_SESSION_ID',
  STRIPE_SESSION_NOT_FOUND = 'STRIPE_SESSION_NOT_FOUND',

  //Wishlist
  WISHLIST_NOT_FOUND = 'WISHLIST_NOT_FOUND',

  //Orders
  ORDER_NOT_FOUND = 'ORDER_NOT_FOUND',
  ORDER_ALREADY_REGISTERED = 'ORDER_ALREADY_REGISTERED',

  //Common
  CRITICAL_INTERNAL_SERVER_ERROR = 'CRITICAL_INTERNAL_SERVER_ERROR',
}
