export const DEFAULT_GET_TRENDING_PRODUCTS_LIMIT = 15;
export const DEFAULT_GET_BEST_SELLERS_LIMIT = 15;
export const DEFAULT_GET_NEW_ARRIVALS_LIMIT = 15;

export const DEFAULT_SEARCH_PRODUCTS_LIMIT = 8;
